Bouwmarkt/Models/ErrorViewModel.cs
namespace Bouwmarkt.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bouwmarkt/Models/Vestiging.cs
using System.ComponentModel.DataAnnotations;

namespace Bouwmarkt.Models
{
    public class Vestiging
    {
        [Key]
        [Display(Name = "Vestigingsnummer")]
        public int VestigingsNummer { get; set; }
        [Required(ErrorMessage = "Naam is verplicht")]
        public string Naam { get; set; }
        [Required(ErrorMessage = "Adresgegevens zijn verplicht")]
        public string Adres { get; set; }
        [Required(ErrorMessage = "Plaatsnaam is verplicht")]
        public string Plaats { get; set; }
        [Display(Name = "Telefoonnummer")]
        [Required(ErrorMessage = "Telefoonnummer is verplicht")]
        public string TelefoonNummer { get; set; }
    }
}

Bouwmarkt/Controllers/HomeController.cs
using Bouwmarkt.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bouwmarkt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bouwmarkt/Controllers/VestigingController.cs
using Bouwmarkt.Data;
using Bouwmarkt.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bouwmarkt.Controllers
{
    public class VestigingController : Controller
    {
        private readonly ApplicationDbContext _db;

        public VestigingController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Vestiging> objVestigingList = _db.Vestigingen;
            return View(objVestigingList);
        }

        // GET: Vestiging
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vestiging/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Vestiging obj)
        {
            if (ModelState.IsValid)
            {
                _db.Vestigingen.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }




        // GET: Vestiging/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var vestigingVanDb = _db.Vestigingen.Find(id);

            if (vestigingVanDb == null)
            {
                return NotFound();
            }
            return View(vestigingVanDb);
        }

        // POST: Vestiging/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Vestiging obj)
        {
            if (ModelState.IsValid)
            {
                _db.Vestigingen.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }




        // GET: Vestigings/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var vestigingVanDb = _db.Vestigingen.Find(id);

            if (vestigingVanDb == null)
            {
                return NotFound();
            }
            return View(vestigingVanDb);
        }

        // POST: Vestiging/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Vestigingen.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            _db.Vestigingen.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Bouwmarkt/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welkom</h1>
    <p>Klik hierboven op de link Vestiging om de lijst met vestigen te zien en de CRUD operations te testen.</p>
</div>

Bouwmarkt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bouwmarkt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bouwmarkt.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bouwmarkt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Vestiging" asp-action="Index">Vestiging</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bouwmarkt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bouwmarkt/Views/Vestiging/Create.cshtml
@model Vestiging

<form method="post">
    <div class="border-bottom p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Voeg vestiging toe</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Naam"></label>
            <input asp-for="Naam" class="form-control" />
            <span asp-validation-for="Naam" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Adres"></label>
            <input asp-for="Adres" class="form-control" />
            <span asp-validation-for="Adres" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Plaats"></label>
            <input asp-for="Plaats" class="form-control" />
            <span asp-validation-for="Plaats" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TelefoonNummer"></label>
            <input asp-for="TelefoonNummer" class="form-control" />
            <span asp-validation-for="TelefoonNummer" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Voeg toe</button>
        <a asp-controller="Vestiging" asp-action="Index" class="btn btn-secondary" style="width:150px">Terug naar lijst</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Bouwmarkt/Views/Vestiging/Delete.cshtml
@model Vestiging

<form method="post" asp-action="Delete" >
    <input asp-for="VestigingsNummer" hidden />
    <div class="border-bottom p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Wis vestiging</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Naam"></label>
            <input asp-for="Naam" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Adres"></label>
            <input asp-for="Adres" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Plaats"></label>
            <input asp-for="Plaats" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="TelefoonNummer"></label>
            <input asp-for="TelefoonNummer" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Wissen</button>
        <a asp-controller="Vestiging" asp-action="Index" class="btn btn-secondary" style="width:150px">Terug naar lijst</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Bouwmarkt/Views/Vestiging/Edit.cshtml
@model Vestiging

<form method="post" asp-action="Edit" >
    <input asp-for="VestigingsNummer" hidden />
    <div class="border-bottom p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Wijzig vestiging</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Naam"></label>
            <input asp-for="Naam" class="form-control" />
            <span asp-validation-for="Naam" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Adres"></label>
            <input asp-for="Adres" class="form-control" />
            <span asp-validation-for="Adres" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Plaats"></label>
            <input asp-for="Plaats" class="form-control" />
            <span asp-validation-for="Plaats" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TelefoonNummer"></label>
            <input asp-for="TelefoonNummer" class="form-control" />
            <span asp-validation-for="TelefoonNummer" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Bijwerken</button>
        <a asp-controller="Vestiging" asp-action="Index" class="btn btn-secondary" style="width:150px">Terug naar lijst</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Bouwmarkt/Views/Vestiging/Index.cshtml
@model IEnumerable<Vestiging>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row p-4">
        <div class="col-6">
            <h2 class="text-primary">Vestiging Lijst</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Vestiging" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-lg"></i>&nbsp;Voeg nieuwe vestiging toe</a>
        </div>
    </div>





    <table class="table table-bordered table-striped" style="width:100%">
        <thead></thead>
        <tr>
            <th>
                Vestigingsnummer
            </th>
            <th>
                Naam
            </th>
            <th>
                Adres
            </th>
            <th>
                Plaats
            </th>
            <th>
                Telefoonnummer
            </th>
            <th>

            </th>
        </tr>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="10%">
                        @obj.VestigingsNummer
                    </td>
                    <td width="20%">
                        @obj.Naam
                    </td>
                    <td width="20%">
                        @obj.Adres
                    </td>
                    <td width="15%">
                        @obj.Plaats
                    </td>
                    <td width="15%">
                        @obj.TelefoonNummer
                    </td>
                    <td>
                        <div class="w-200 btn-group" role="group">
                            <a asp-controller="Vestiging" asp-action="Edit" asp-route-id="@obj.VestigingsNummer"
                            class="btn btn-primary mx-2"><i class="bi bi-pencil"></i>&nbsp;Wijzig</a>
                            <a asp-controller="Vestiging" asp-action="Delete" asp-route-id="@obj.VestigingsNummer"
                            class="btn btn-danger mx-2"><i class="bi bi-trash3"></i>&nbsp;Wissen</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>